parameters:
    deejff_data_grid.limit_on_page: 10
    deejff_data_grid.data_grid_builder.class: Deejff\DataGridBundle\DataGrid\DataGridBuilder

services:
    deejff_data_grid.service.data_grid_builder:
        class: %deejff_data_grid.data_grid_builder.class%
        arguments:
            - "@form.factory"
            - "@knp_paginator"
            - %deejff_data_grid.limit_on_page%
